travis:
  secure:
    BINSTAR_TOKEN: Xwl4nODxsfk/KwN4xxqf5uxgqTyI+xwY6EpziONLHlsmZPcy5e1ZHbhOHU8OahgnH78dFkZfI/7oyNKMlckUbmiIvqqOAFnzH2pZikdE+k+wHPAe7S7LHZKv0mCOAtxDuMVB30thSF2gPUKk35tx7OwhAX4VsQL7rycxJBmotqsuodkKZFcnxN8r9ZieBEgbq6lh/ZscgkDIcdTeDbbNpobKcwj7lcDLcQoZm3KEd0toL7X+6Ycs7rLkoUmh4GesjBrl+9UMwe1CKYqAvFE49yL0MAe1w4LVlhvGHBMX7iPON3KEYFqO9qKgE5Se8l/dqLOTubNJhEdn3ItsmovrX7COmXSDffmIn7Y5VsgZtRIXmgtTZxw5iNyUb86yfuKCU07m+iLinsqdhnVj2eHbQ4gtzGJmDwRgknS/b+JJ+SWcoTo7frUVBLgEtbhZhVRu5v+9sF9gAgoUonHaSzzuNgX4+FLLmKmC5vkaDFjhtewOZmnxX8pEj+ip1vLbwc8XndJMxvh1t0rWCTsxfn9dBAoOp9BWVGEsLBNxGfLvzwtIKhnwE3/PqgLukHcdUFwF3R1jXHlM+B9MDcEph8VVt8KjLsn9igUpV2cUjMShHuFekIW0lFUdj60PrlWvvkWx9yIOVHnJ7PsR7Yq8Y87pKzme0qwK4HfFJnqMaWZe+iQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
