travis:
  secure:
    BINSTAR_TOKEN: GyeTrX735Ik5t+q6U92ARjz4XiBpa37/DBGVnxsF2Kv017oeQvwXqLlAGCJYOM94HQjzhGkypkq/SyzEVNo6UR8yQb5GctCQYRyfW+QypuYb4VdbIeJIFvMf1lnubpvgumQBbBEbROjqP2VcMPS8189yHRI4iFLaolaFvzPJm3/weuVrCgqqbzZY/xI+nf3NylYfLI96BTPMATVLuqfn6cnReCRmlK0QHQ2FFPnvmDmt4auvd6G0/pQKvj5Fi7cO4nVcWGCNUbkxDwyZC/yduTiFjG589P4Bm6yXwi2lypdOjX2HfRCYwXUt6YnncxgP+xewsyRzonmL9w7ChgUAefp4xUdijqowRqudF5x7llSIanKFZX8WuD+WBnGM+SER3ykVOfrXR5qk76XPMuJargCs4EntesM7HP4hMXTkzFDh+eoOcdlf51o6/PtSXzBnX23AHcO3cMUMGeG8A//MgR2EQXeskDkQO5/2h75Fmp53WMLQcoCGa8yDy7ecjZ6FSokKc9iaDuNJyvEVOus/j//WlDgqCW/HTtVAtJBDFivN1mHCb1OXdd30MkE8HSel1rFEVg5Bz+oTLbeXkrdzoVykdGSfPw9xkB9QWF7w0Jzok/qbJNXMw/P5NMxsYLhMntLHVITACl+NCwKOOmKeLtsVsnRYcObSM690PUSJ5uc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
